### ISSUE TITLE
There is no images or countdown in the landing page

### ISSUE THREAD

**Issue by anishshobithps** [gdscsjec/tiara2024#24]
It happened after #15

**Comment by Vyshnav001** [comment]
import { nextui }  from "@nextui-org/react";
 // nextui(),
 
 
 this is the issue
which is in tailwind.config

**Comment by anishshobithps** [comment]
> this is the issue
> which is in tailwind.config

Oh ? damm it

**Comment by anishshobithps** [comment]
Fixed in https://github.com/tiarasjec/website/commit/e5e34e0993afe16314f765e1cc20c54f33b81a0c
