### ISSUE TITLE
feat: Improve UX by adding event route component in landing page

### ISSUE THREAD

**Issue by rabilrbl** [gdscsjec/tiara2024#53]
- Remove the `Tiara Registrations out now!`
- Add the existing event route page at the end of Home page
- Add a register now button at the very bottom 

This design specially focus on mobile users as they view the landing page and navigate to event categories or register after scrolling, enhances UX.

**Comment by joywin2003** [comment]
On it!!

**Comment by joywin2003** [comment]
Fixed it, made a PR
